"""empty message

Revision ID: ff12b4cebbd7
Revises: 4fcc7b08bbff
Create Date: 2020-06-05 23:05:53.340318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff12b4cebbd7'
down_revision = '4fcc7b08bbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('createddatetime', sa.DateTime(), nullable=False))
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('show', sa.Column('createddatetime', sa.DateTime(), nullable=False))
    op.add_column('show', sa.Column('description', sa.String(), nullable=True))
    op.add_column('show', sa.Column('endtime', sa.DateTime(), nullable=False))
    op.add_column('show', sa.Column('starttime', sa.DateTime(), nullable=False))
    op.add_column('venue', sa.Column('createddatetime', sa.DateTime(), nullable=False))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('venue', 'seeking_artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_artist', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'createddatetime')
    op.drop_column('show', 'starttime')
    op.drop_column('show', 'endtime')
    op.drop_column('show', 'description')
    op.drop_column('show', 'createddatetime')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'createddatetime')
    # ### end Alembic commands ###
